### ISSUE TITLE
LS_USER and LS_GROUP hard-coded in debian upstart conf template

### ISSUE THREAD

**Issue by mattcl** [elastic/puppet-logstash#168]
LS_USER and LS_GROUP are hard-coded to "logstash" which makes configuring the user that runs logstash. It would be nice to have these configurable or at least pick up the logstash user from the module

**Comment by igalic** [comment]
<blockquote class="twitter-tweet" lang="en"><p>&quot;i&#39;ve seen this code-path. this should be working.&quot;&#10;&#10;later&#10;&#10;&quot;yeah, i remember now where i&#39;ve seen that code-path: in my unmerged patch.&quot;</p>&mdash; The Wrath of PB™ (@hirojin) <a href="https://twitter.com/hirojin/status/572824994083958785">March 3, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by jarpy** [comment]
The example above is correct these days. :+1:
