### ISSUE TITLE
CentOS init crashing

### ISSUE THREAD

**Issue by cdenneen** [elastic/puppet-logstash#185]
I've started logstash outside of init provided in 0.5.1 and no problems so something in it is causing process to die after 20-40 minutes or so. (Maybe NICE).

**Comment by TJM** [comment]
@cdenneen by chance do you have any "init_defaults" specified, I found they need to be quoted in the template.

**Comment by jarpy** [comment]
Hopefully time has healed this wound. Closing the issue.
