### ISSUE TITLE
Refresh causing multiple processes

### ISSUE THREAD

**Issue by cdenneen** [elastic/puppet-logstash#190]
for some reason when using puppet to refresh on config changes a new process is started when old process remains. 
I've seen similar behavior with the init so I think the RH init script needs to be reviewed.

**Comment by jarpy** [comment]
There's [acceptance test coverage](https://github.com/elastic/puppet-logstash/blob/092c4b89c4a969f1a330a9e32be39bff76a68a17/spec/acceptance/class_logstash_spec.rb#L22) for this case now, and it seems to be consistently happy.

I hereby sprinkle this issue with hope and faith, and lay it gently in the closed pile.
