### ISSUE TITLE
logstash::configfile with 'source =>' throws cryptic error

### ISSUE THREAD

**Issue by gdhbashton** [elastic/puppet-logstash#194]
```
  logstash::configfile { 'testinput':
    content => template ('itv_genersys_data/logstash/syslog1514.fragment'),
  }
```

The above works fine - hurrah. However, I originally wanted to try a simple straight file copy as per the README.md:

```
  logstash::configfile { 'testinput':
    source =>  'puppet:///itv_genersys_data/logstash/syslog1514.fragment',
  }
```

(the 'syslog1514.fragment' exists in both files/logstash/ and templates/logstash/)

When I do a puppet run using the 'source' version, I get this mysterious error:

```
Error: /Stage[main]/Logstash::Config/File_concat[ls-config]: Could not evaluate: undefined method `content' for nil:NilClass
```

Weird - I've used the 'template' syntax instead, but either there's a bug or the docs are wrong :)

Cheers,
Gavin.

**Comment by snobear** [comment]
+1 for a better check/error message.  I hit this same error today, and was due to my source path being incorrect.
