### ISSUE TITLE
ensure => absent fails to remove logstash package when logstash-contrib has been installed

### ISSUE THREAD

**Issue by kholloway** [elastic/puppet-logstash#203]
OS: RHEL6
Puppet version: 3.7.3 (both client and master)
Expected behavior: logstash should be uninstalled along with -contrib module if installed

Install logstash and contrib module:
```puppet
class { '::logstash':
  install_contrib => true,
}
```

Now try to remove everything:
```puppet
class { '::logstash':
  ensure => 'absent'
}
```

Resulting error on host:
```
Error: Execution of '/bin/rpm -e logstash-1.4.2-1_2c0f5a1.noarch' returned 1: error: Failed dependencies:
	logstash >= 1.4.2 is needed by (installed) logstash-contrib-1.4.2-1_efd53ef.noarch
	logstash < 1.4.3 is needed by (installed) logstash-contrib-1.4.2-1_efd53ef.noarch
Error: /Stage[main]/Logstash::Package/Logstash::Package::Install[logstash]/Package[logstash]/ensure: change from 1.4.2-1_2c0f5a1 to absent failed: Execution of '/bin/rpm -e logstash-1.4.2-1_2c0f5a1.noarch' returned 1: error: Failed dependencies:
	logstash >= 1.4.2 is needed by (installed) logstash-contrib-1.4.2-1_efd53ef.noarch
	logstash < 1.4.3 is needed by (installed) logstash-contrib-1.4.2-1_efd53ef.noarch
```

**Comment by electrical** [comment]
The logstash module does need some love.
Due to work on Logstash it self i haven't had much time to work on it.
The ES puppet module will have a release soon and the logstash module is up next.
Sorry for the issue you are having :-(

**Comment by kholloway** [comment]
Temporary/simple workaround for anyone else running into this issue.

```puppet
package { 'logstash-contrib':
  ensure => 'absent'
}
class { '::logstash':
  ensure  => 'absent',
  require => Package['logstash-contrib'],
}
```

**Comment by kholloway** [comment]
No problem, I have a simple workaround shown above and if I get time I will fix this in the module itself and send you a PR.

Thanks for taking the time to write this module in the first place, we have found it to be very useful and saved us a considerable amount of time getting Logstash into Puppet.

**Comment by jarpy** [comment]
The `logstash-contribs` package is now deprecated, so we can call this poor old issue "deprecated" too.

Farewell, sweet #203 :crying_cat_face: .
