### ISSUE TITLE
FalseClass

### ISSUE THREAD

**Issue by agonen** [elastic/puppet-logstash#206]
Hi i'm trying to install logstash moudle via vagrant provisioner.
I've installed lastest logstash puppet moudle via puppetforge  
I've run this command :
vagrant provision
and got :
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Error: false is not a string.  It looks to be a FalseClass at /etc/puppet/modules/logstash/manifests/init.pp:218 on node vagrant-ubuntu-trusty-64.att.net
==> default: Error: false is not a string.  It looks to be a FalseClass at /etc/puppet/modules/logstash/manifests/init.pp:218 on node vagrant-ubuntu-trusty-64.att.net
T

my default.pp :

class { 'logstash':
  autoupgrade => true,
  status => 'disabled',
  install_contrib => true,
  java_install => true,
  manage_repo  => true
}

**Comment by electrical** [comment]
Hi,

The reason its failing is because repo_version option is not set.
Due to a bug its not reporting very clear what is expected, sorry for that.
If you set repo_version => '1.4' it should work fine.

**Comment by agonen** [comment]
Great. I give it try thanks for the quick response. Btw does it support 1.5 as well?

**Comment by electrical** [comment]
there is allot of work that needs to be done for making the puppet module support LS 1.5
This is in the planning and hopefully have it ready before LS 1.5 goes GA.

**Comment by agonen** [comment]
Hi seems repo_version worked ok on this error ,
 but I know I get new error  :( , it seems some conflict between logstash puppet and java puppet file.

I'll try to see what i can do . anyhow here is the error : 

==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Cannot alias Package[java] to ["openjdk-7-jre-headless"] at /etc/puppet/modules/java/manifests/init.pp:95; resource ["Package", "openjdk-7-jre-headless"] already declared at /etc/puppet/modules/logstash/manifests/java.pp:58 at /etc/puppet/modules/java/manifests/init.pp:95 on node vagrant-ubuntu-trusty-64
==> default: Wrapped exception:
==> default: Cannot alias Package[java] to ["openjdk-7-jre-headless"] at /etc/puppet/modules/java/manifests/init.pp:95; resource ["Package", "openjdk-7-jre-headless"] already declared at /etc/puppet/modules/logstash/manifests/java.pp:58
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Cannot alias Package[java] to ["openjdk-7-jre-headless"] at /etc/puppet/modules/java/manifests/init.pp:95; resource ["Package", "openjdk-7-jre-headless"] already declared at /etc/puppet/modules/logstash/manifests/java.pp:58 at /etc/puppet/modules/java/manifests/init.pp:95 on node vagrant-ubuntu-trusty-64
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what

**Comment by agonen** [comment]
A new problem , I've removed the java required in the puppet , not it failed on looking for key D88E42B4 : 
root@vagrant-ubuntu-trusty-64:/etc/init.d# /usr/bin/apt-key adv --keyserver pgp.mit.edu --recv-keys D88E42B4
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.eucXy4sC4c --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg --keyring /etc/apt/trusted.gpg.d/ubuntu-mozilla-daily-ppa.gpg --keyring /etc/apt/trusted.gpg.d/webupd8team-java.gpg --keyserver pgp.mit.edu --recv-keys D88E42B4
gpg: requesting key D88E42B4 from hkp server pgp.mit.edu
gpgkeys: key D88E42B4 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0


Now I've tried to search online http://pgp.mit.edu/pks/lookup?search=D88E42B4&op=index , but no keys found ... 
any idea how to progress from here ?

**Comment by agonen** [comment]
ok , found issue #191  on the PGP . I've change to use file key but not it seems to failed on key validation : 

==> default: Error: validate_re(): "46095ACC8548582C1A2699A9D27D666CD88E42B4" does not match ["\\A(0x)?[0-9a-fA-F]{8}\\Z", "\\A(0x)?[0-9a-fA-F]{16}\\Z"] at /etc/puppet/modules/apt/manifests/key.pp:60 on node vagrant-ubuntu-trusty-64
==> default: Error: validate_re(): "46095ACC8548582C1A2699A9D27D666CD88E42B4" does not match ["\\A(0x)?[0-9a-fA-F]{8}\\Z", "\\A(0x)?[0-9a-fA-F]{16}\\Z"] at /etc/puppet/modules/apt/manifests/key.pp:60 on node vagrant-ubuntu-trusty-64

**Comment by jarpy** [comment]
The module now ships with a [Vagrantfile](https://github.com/elastic/puppet-logstash/blob/master/Vagrantfile) for expermental testing. It should also serve as a good example for making awesome Vagrantfiles of your own. :)
