### ISSUE TITLE
Incompatible with Puppet Apt 2.0.0 module

### ISSUE THREAD

**Issue by teran-mckinney** [elastic/puppet-logstash#214]
With Apt 2.0.0, some things were moved around for apt::source.

https://github.com/puppetlabs/puppetlabs-apt/blob/master/CHANGELOG.md#2015-04-07---supported-release-200

puppet-logstash is incompatible here: https://github.com/elastic/puppet-logstash/blob/master/manifests/repo.pp#L44

The necessary changes will probably look like this: https://github.com/sensu/sensu-puppet/pull/348/files

I'm not certain if you all want this to be compatible with Apt 2.X or not, but some modules are already moving over to it, breaking past compatibility.

Thanks,
Teran

**Comment by electrical** [comment]
Hi,

Since i support older versions of PE some of them are unable to upgrade the apt module and because of that i have to support the older way of handing it.
Hopefully at some point i'll be able to ditch the support and upgrade to apt 2.x

**Comment by bflad** [comment]
First off, thanks for helping build and support this super awesome module. You've certainly made things much easier for everyone in the community by providing this module and its functionality.

Would it be reasonable to release a new major version of this module and note the compatibility difference at the top of the README? From my Chef cookbook background this was the path of least resistance to support both the sets of customers when critical backend dependencies changed. It's only going to get worse as time goes if we're only supporting the older clients and may cause module usage fragmentation, which isn't good for anyone.

I think there will be plenty who may have inadvertently went down the apt 2.x upgrade path not realizing the implications. Also, new folks are going to be starting with 2.x unknowingly and going to have a bad experience with this (and admittedly other) modules.

We can branch the current major version, make the README note, and backport fixes from master as necessary. A little extra work for sure, but in the end a much happier community. What do you think?

**Comment by sjahl** [comment]
+1 on maintaining a separate branch. I think it would make sense to keep a branch that tracks puppet open source, and future parser compatibility. Seems like a good thing to do so the module is ready once "future" parser features become "current" in puppet enterprise.

**Comment by daks** [comment]
I thought someone was working on making the module compatible with puppetlabs/apt 2.0 while preserving the possibility to have a 1.x version.

**Comment by madAndroid** [comment]
As mentioned in https://github.com/elastic/puppet-elasticsearch/issues/322#issuecomment-118876894, this is something Puppetlabs have addressed in the latest release of puppetlabs-apt: https://github.com/puppetlabs/puppetlabs-apt/blob/master/CHANGELOG.md#2015-06-16---supported-release-210

Other modules which have the same dependency have been able to change only the `metadata.json`, since backwards compatibility with 1.8 is now supported

**Comment by jarpy** [comment]
The `metadata.json` file doesn't have `puppetlabs/apt` in it at the moment, so it seems it's left to the user to install whichever version they like. I'm not sure that's a good design, but it should solve this issue.

In future, I'll look to manage the `puppetlabs/apt` dependency properly.
