### ISSUE TITLE
Should the latest version work with LS 1.5.0-1?

### ISSUE THREAD

**Issue by cwneal** [elastic/puppet-logstash#216]
I'm having issues with it that I cannot explain.  I'm using the latest puppet-logstash module, and give it a package_url pointing to the 1.5.0-1 RPM, and everything installs fine, but when the service is started, after initializing everything and starting the flow, no events are processed.

I'm have an input of some Apache access/error logs, use the APACHECOMBINED filter, and output to Kafka and ES.

The interesting thing is that if I run logstash from the CLI with the same config file, events are processed fine.  So there seems to be *something* related to the way the service is set up perhaps that is causing issues?

Can I provide any more information?
I'm seriously stumped on this one.
Thank you!
Chris

**Comment by mrbanzai** [comment]
I haven't tried it yet, but if you're installing from the RPM, you might be able to provide the initscript from the RPM (as a template, though there don't appear to be any replacements in it) to the `init_template` parameter, as a stopgap.

**Comment by mrbanzai** [comment]
As a sidenote, it doesn't appear that there's a way to have the module not manage the initscript?

**Comment by cwneal** [comment]
My apologies for leaving this open.  It does work fine with 1.5.0.  My issue ended up being permissions on the since_db path directory :S.
I will close this.
Thanks for the followup.
