### ISSUE TITLE
logstash::patternfile puts file into wrong directory

### ISSUE THREAD

**Issue by bastelfreak** [elastic/puppet-logstash#224]
the default behavior is to put the grok pattern into /etc/logstash/patterns(${logstash::configdir}/patterns), if you restart logstash, you get the following error message:

```
{:timestamp=>"2015-06-10T14:02:58.081000+0200", :message=>"The error reported is: \n  pattern %{DATE_SSO:timestamp} not defined"}
```

this is fixed by moving the pattern into the right directory:

```
cp /etc/logstash/patterns/sso_patterns /opt/logstash/patterns/
```

my pattern resource (with my [patch](https://github.com/elastic/puppet-logstash/pull/223)):

```
  logstash::patternfile {'parallels_date_pattern':
    content   => 'DATE_SSO %{MONTHNUM}[/-]%{MONTHDAY}%{SPACE}%{TIME}',
    filename  => 'sso_patterns',
  }
```

and my logstash class:

```
  class { '::logstash':
    manage_repo   => true,
    repo_version  => '1.5',
    init_defaults => $config_hash,
    autoupgrade   => true,
  }
```

**Comment by joshuaspence** [comment]
+1. Pattern files should be stored in `/opt/logstash/patterns` rather than `/etc/logstash/patterns`.

**Comment by jarpy** [comment]
Everything has moved around under Logstash 5, and the module uses current default locations. Hopefully there's no more issue here.
