### ISSUE TITLE
When will a new release come out?

### ISSUE THREAD

**Issue by JimPanic** [elastic/puppet-logstash#226]
I'm currently pinning all the puppet modules in my environment and want to use releases instead of commits, so a release that is less than a year old would be nice. Any plans?

**Comment by electrical** [comment]
Hi,

the current planning is to get the ES puppet module to a point where we tag it as our 1.0 release.
When that's done all the improvements we have done there will be ported over to the logstash module and will include all kinds of other improvements specifically for the LS puppet module.

We've decided to do this to avoid doing duplicate work on both module and making sure that we end up with all our module with a very strong base structure.

**Comment by cdenneen** [comment]
+1

**Comment by cdenneen** [comment]
@electrical any update on 1.0 release of ES puppet module and update to this as well?

**Comment by madAndroid** [comment]
Would be great if a new tag/release could be cut, even if it's just a feature release that covers all the most recent changes - there are bug fixes in master that we're currently using, but would prefer to avoid using either `origin/master` or a commit hash/ref in our Puppetfile, to more easily identify would version we're currently on.

**Comment by jarpy** [comment]
Version `0.6.0` is now live on the Puppet Forge, bringing Logstash 2.0 support and new-style plugin management.

Most importantly, it's all covered by a heavily refactored behavioural test suite, so we can get back to a reasonable development/release cadence.
