### ISSUE TITLE
Logstash config files are not purged under ${logstash::configdir} folder

### ISSUE THREAD

**Issue by szemlyanoy** [elastic/puppet-logstash#232]
Hey guys,

seems purge of config files located under ${logstash::configdir}/conf.d is not working!
Purge on ${logstash::configdir} level works, but not further.
I turned purging on by passing hiera value
logstash::purge_configdir: true

but it just doesn't clean up non-managed files.
Sounds like an issue or I missed something?

Regards
Sergey

**Comment by jarpy** [comment]
Config purging has been rewritten with changed behaviour. Hopefully this issue is now resolved.

See: https://github.com/elastic/puppet-logstash/issues/312#issuecomment-266331411
