### ISSUE TITLE
Could not autoload puppet/provider/file_concat/posix: cannot load such file

### ISSUE THREAD

**Issue by RJ3000** [elastic/puppet-logstash#233]
Hey, 

Having issues using the logstash module, when using v0.3 of the ispavailability/file_concat module, we get the following error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: 
Could not autoload puppet/type/file_concat: Could not autoload puppet/provider/file_concat/posix:
cannot load such file -- puppet/provider/file_concat on node
```

Using Version 1.0.1 of the "electrical-file_concat" (seen another issue that recommended updating file_concat) module, we get the same error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: 
Could not autoload puppet/type/file_concat: Could not autoload puppet/provider/file_concat/posix: cannot load such file -- puppet/provider/file_concat on node ....
```  

Puppet Agent Version: 3.8.1
OS: CentOS 7.0. (Also tested against CenOS 6.5)

Any suggestions on a work around for this issue?

Many thanks,

**Comment by electrical** [comment]
Hi,

The latest one from electrical-file_concat should not have that issue. You most likely have the old version still somewhere in your module list.
Can you check?

**Comment by RJ3000** [comment]
```
Checking the Version in Use:

# head modules/file_concat/metadata.json
{
  "name": "electrical-file_concat",
  "version": "1.0.1",
  "author": "electrical",
```

Can see the contents of the file change and removing files after the update:

```
Notice: /File[/var/lib/puppet/lib/puppet/provider/file_concat.rb]/ensure: removed
Notice: /File[/var/lib/puppet/lib/puppet/type/file_fragment.rb]/content: content changed '{md5}51cf10358174ebc3b4b086120f33f6e9' to '{md5}2592604e4df18d712cc2d7712314c96e'
.....
```

Sadly, same issue

**Comment by electrical** [comment]
Hmm, did it ever remove the other old files? the provider part is removed

**Comment by RJ3000** [comment]
Looks like it removes the provider and the provider directory 

https://gist.github.com/RJ3000/e2a780821f755dee318e

**Comment by electrical** [comment]
Strange its still giving that error. Can you restart the puppet master? something must be caching something stupid

**Comment by RJ3000** [comment]
Given it a few restarts, the error continues.  Having a look for more places this could be cached at

**Comment by RJ3000** [comment]
Looks to be an issues with R10k:

https://tickets.puppetlabs.com/browse/PUP-1515

Once we updated the module in our default environment, the logstash module is able to run.

Thanks for your help

**Comment by electrical** [comment]
Ah, interesting. weird stuff :-)
