### ISSUE TITLE
Template in elasticsearch output not used when service first started

### ISSUE THREAD

**Issue by madAndroid** [elastic/puppet-logstash#236]
I've got an odd situation where a custom template I've created doesn't get used to create an index in ES when logstash first starts .. when I set the service to `unmanaged`, and then start the service manually, then the template is used to create the index... leading me to believe this is something to do with the way the config is getting created prior to the service being started.

The output of the module shows that the service is started after the template is provisioned, and after the file_concat resource is done managing the logstash config:
```puppet
==> consul: Notice: /Stage[main]/Profile_logstash/File[/etc/logstash/templates]/ensure: created
==> consul: Notice: /Stage[main]/Profile_logstash/File[/etc/logstash/templates/outputs]/ensure: created
==> consul: Notice: /Stage[main]/Profile_logstash/File[/etc/logstash/templates/outputs/elasticsearch-template.json]/ensure: defined content as '{md5}46552ca056b95b3a70a9b623cc76281d'
==> consul: Info: /Stage[main]/Profile_logstash/File[/etc/logstash/templates/outputs/elasticsearch-template.json]: Scheduling refresh of Class[Logstash::Service]
==> consul: Notice: /Stage[main]/Logstash::Config/File_concat[ls-config]/ensure: created
==> consul: Info: /Stage[main]/Logstash::Config/File_concat[ls-config]: Scheduling refresh of Class[Logstash::Service]
==> consul: Info: Class[Logstash::Service]: Scheduling refresh of Logstash::Service::Init[logstash]
==> consul: Info: Logstash::Service::Init[logstash]: Scheduling refresh of Service[logstash]
==> consul: Notice: /Service[logstash]: Triggered 'refresh' from 1 events
```
The entries in the ES logs show the index not being created with the template when the service is managed:
```
[2015-07-22 20:03:43,555][INFO ][cluster.metadata         ] [consul-es-logstash] [logstash-2015.07.22] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings [syslog]
[2015-07-22 20:03:43,785][INFO ][cluster.metadata         ] [consul-es-logstash] [logstash-2015.07.22] update_mapping [syslog] (dynamic)
```
When setting the service to `unmanaged`, and starting the process manually, the template is used:
```
[2015-07-22 20:31:48,834][INFO ][cluster.metadata         ] [consul-es-logstash] [logstash-2015.07.22] creating index, cause [auto(bulk api)], templates [logstash], shards [5]/[1], mappings [syslog, _default_]
[2015-07-22 20:31:49,170][INFO ][cluster.metadata         ] [consul-es-logstash] [logstash-2015.07.22] update_mapping [syslog] (dynamic)
```
Is there any debugging I can do/provide to confirm the issue is not occuring in the logstash puppet module? I've created an issue for the logstash-elasticsearch plugin here: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/211

**Comment by madAndroid** [comment]
Closing this now, as we were able to resolve this be specifying a custom template

**Comment by electrical** [comment]
Hmm, interesting. I must admit that the logstash module is horribly out of date and requires some decent work which is on the list which in turn will hopefully solve these kind of issues.
