### ISSUE TITLE
Updated APT module warns if not using 40char keys for repo

### ISSUE THREAD

**Issue by geoffr** [elastic/puppet-logstash#237]
Hi,

After updating the puppetlabs-apt module you now get a warning when not using the 40 char key:

Warning: /Apt_key[Add key: D88E42B4 from Apt::Source logstash]: The id should be a full fingerprint (40 characters), see README.

So the change needed:

--- a/modules/logstash/manifests/repo.pp
+++ b/modules/logstash/manifests/repo.pp
@@ -35,7 +35,7 @@ class logstash::repo {
         location    => "http://packages.elasticsearch.org/logstash/${logstash::repo_version}/debian",
         release     => 'stable',
         repos       => 'main',
-        key         => 'D88E42B4',
+        key         => '46095ACC8548582C1A2699A9D27D666CD88E42B4',
         key_server  => 'pgp.mit.edu',
         include_src => false,
       }

**Comment by electrical** [comment]
Hi,

Due to complications i have decided not to support it yet. See https://github.com/elastic/puppet-elasticsearch/pull/320 for more details.
