### ISSUE TITLE
Multiple Broker/Indexers ingesting

### ISSUE THREAD

**Issue by cdenneen** [elastic/puppet-logstash#239]
@jordansissel @electrical 
This might not be the best place for this but figured I'd ask about the ability or maybe how would you have multiple logstash servers (for HA) possibly pulling from same s3 input but doesn't share sincedb_path.
Could you use a NFS/GFS filesystem and have more than one instance of logstash using the same sincedb file?
This might not even be possible but would be really helpful when s3 input threads might die (logstash still running) and now ingestion has stopped. 
Obviously fixing the s3 input thread from dying is the correct fix but for HA if the LS node died it would be nice if you could have 2 running so could fix node without downstream data loss/backup/delay.

**Comment by jordansissel** [comment]
@cdenneen Good idea! Would you mind opening this for discussion here: https://github.com/logstash-plugins/logstash-input-s3 ?

**Comment by cdenneen** [comment]
@jordansissel Thanks! Done! Added https://github.com/logstash-plugins/logstash-input-s3/issues/49
