### ISSUE TITLE
Unable to find module 'ispavailability-file_concat' on https://forgeapi.puppetlabs.com

### ISSUE THREAD

**Issue by Dharmender-Singh** [elastic/puppet-logstash#244]
Hi,
I am trying to use this module but getting following error: Message: Unable to find module 'ispavailability-file_concat' on https://forgeapi.puppetlabs.com

I checked this module on forge-api and its exist.
![image](https://cloud.githubusercontent.com/assets/12389415/10734918/79ea1396-7bfd-11e5-8748-b2173af61416.png)

Details : Puppet 3.8.4
              librarian-puppet 2.2.1

Could anybody help me with this problem?

Thanks & Regards
Dharmender

**Comment by electrical** [comment]
Hi,

Can you try this one? https://forge.puppetlabs.com/electrical/file_concat
I moved it at some point but never updated the logstash module so far since i haven't done a new release yet.

**Comment by Dharmender-Singh** [comment]
Hi,

Thanks for your reply. I am using Puppet file with this:
mod "elastic/puppet-logstash",
:git => "https://github.com/elastic/puppet-logstash.git",
:ref => 'e972df79eaa7a0399e56e1173d49a4dcdb9ca7be'

Should I fork your repo and then change the metadata.json file ? or is there any other way for resolving this.

Thanks & Regards
Dharmender

**Comment by electrical** [comment]
Hi,

I think its best to fork it for now until I make the required modifications.
Eventually the concat part will be removed entirely since logstash supports multiple files nicely anyway.

**Comment by Dharmender-Singh** [comment]
Hi,
I have changed the metadata.json with:
 "name": "electrical/file_concat",
 "version_requirement": ">= 1.0.1"

But now I am getting this error:
Message: Unable to find module 'electrical-file_concat' on https://forgeapi.puppetlabs.com

-Dharmender

**Comment by electrical** [comment]
That is very weird.. I would contact the forge people to find out what's wrong, puppet module install parts work fine last i checked.

**Comment by Dharmender-Singh** [comment]
Thanks :+1:  I will wait for your positive response.

Regards
Dharmender

**Comment by Dharmender-Singh** [comment]
Hi,

Is there any update on this?  Can we resolve this problem by providing GitHub reference URL on metadata.json or any other way?

Thanks 
Dharmender

**Comment by electrical** [comment]
I can update the metadata.json file to point to the new location. but according to your try that failed as well?
because of that i think its a bug in librarian-puppet

**Comment by Dharmender-Singh** [comment]
hmm..yes. Can you update the metadata.json file? I can try that again, and if it;s not working then I will update my librarian-puppet version.

**Comment by electrical** [comment]
I'll update the file later today and let you know.

**Comment by Dharmender-Singh** [comment]
Thanks :+1:

**Comment by jarpy** [comment]
Hello. `ispavailability/file_concat` has now been fully replaced with `electrical/file_concat`.

That provides a stable solution for now, but we can clearly go one better with direct fragment support from Logstash.

Thank you.
