### ISSUE TITLE
Debian 8, Logstash 2 support

### ISSUE THREAD

**Issue by kasperbrandenburg** [elastic/puppet-logstash#245]
Hi,

Will this module get Debian8 support and Logstash 2.0 support? and of course puppet 4.x
Update: it would appear file_concat is not a ressource available in 4.2.2.

**Comment by jarpy** [comment]
I'm going to split these out to separate issues to track them better, I hope you don't mind.

- Debian is supported and tested now.
- Logstash 2.0 is tracked in #249 (and the new plugin system is now supported).
- Let's track Puppet 4 support in #269.

Thanks.
