### ISSUE TITLE
first puppet run: Could not autoload puppet/type/file_concat:

### ISSUE THREAD

**Issue by ltutar** [elastic/puppet-logstash#248]
I get the following error with the first puppet run. The second run works fine.

[root@elkagent ~]# puppet --version
4.2.2

elasticsearch-logstash (v0.5.1)

CentOS Linux release 7.1.1503 (Core) 

[root@elkagent ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/file_concat: Could not autoload puppet/provider/file_concat/posix: no such file to load -- puppet/provider/file_concat at /etc/puppetlabs/code/environments/production/modules/logstash/manifests/config.pp:55:5 on node elkagent.home
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by electrical** [comment]
Hi,

The file_concat module that is referenced is broken indeed.
If you replace it with https://forge.puppetlabs.com/electrical/file_concat  should solve the issue.

**Comment by ltutar** [comment]
file_concat from electrical works. Thank you.
