### ISSUE TITLE
Logstash 2.0 support

### ISSUE THREAD

**Issue by paul-cs** [elastic/puppet-logstash#249]
Is this project going to be updated to support logstash 2.0?

Looking back through the other issues this seems to be asked lots and there seems to be no answer forth coming from elastic. Can we get a concrete timeframe for some progress for this project?

**Comment by ltutar** [comment]
+1

**Comment by mkrakowitzer** [comment]
+1

**Comment by bhaku** [comment]
:+1:

**Comment by ltutar** [comment]
In the meantime, logstash 2.1 is released yesterday

**Comment by MikeMcMahon** [comment]
we really need this, we utilize logstash 2.1 for some features only present in that version.

**Comment by shaunrampersad** [comment]
+1

**Comment by beeva-diegogarcia** [comment]
+1

**Comment by brhahlen** [comment]
+1

**Comment by rabbenhuis** [comment]
+1

**Comment by SanderSander** [comment]
+1

**Comment by FireDrunk** [comment]
+1

**Comment by cdenneen** [comment]
@electrical I know you were waiting til 2.0 release of all the changes to es module to port back here. Any update on the status of this?

**Comment by cdenneen** [comment]
To rest of thread what issues are you facing? I've installed 2.0 and 2.1 on CentOS with this module just fine.

**Comment by shaunrampersad** [comment]
Hi @cdenneen 
I've deployed logstash 2 with this module and then tried to send output from filebeat. Logstash needed the filebeat plugin to be installed and I could not do that with the current module. 
I've created my own module to download the logstash tarball which includes all the plugins I need. 

Thanks
shaun

**Comment by cdenneen** [comment]
Here is basically what I did... I created a profile::logstash which includes the logstash module here.

I then added this define type:

```puppet
define profile::logstash::plugin_install {
  if $name =~ /\.\d$/ {
    $plugininfo = split($name, '-')
    $pluginname = "${plugininfo[0]}-${plugininfo[1]}-${plugininfo[2]}"
    $pluginver = $plugininfo[3]
    $command = "/opt/logstash/bin/plugin install --version ${pluginver} ${pluginname}"
  }else{
    $command = "/opt/logstash/bin/plugin install ${name}"
  }
  exec {"installing ${name}":
    path    => ['/bin', '/usr/bin'],
    command => $command,
    unless  => "test -d /opt/logstash/vendor/bundle/jruby/1.9/gems/${name}*",
    require => Class[::logstash]
  }
}
```
This defined type allowed me to install modules as normal and even specify particular versions.

Then inside my `profile::logstash` I've included:

```puppet
profile::logstash::plugin_install { ['logstash-codec-cloudtrail', 'logstash-codec-plain', 'logstash-filter-prune', 'logstash-filter-translate', 'logstash-input-sqs-1.1.0', 'logstash-input-lumberjack-1.0.5', 'logstash-filter-mutate-1.0.2']: }
```

While this probably isn't the best solution because it hardcodes paths and jruby version... it was a useable solution until @electrical ports all the ES changes back into this module.

Hope this helps

**Comment by ltutar** [comment]
I can also install logstash 2.2.0 with the module. 
I had the following output with logstash version 1.5.6:
```
output {
  elasticsearch {
    host => "localhost"
    port => 9200
    protocol => "http"
    manage_template => false
  }
}
```
and had to change it to
```
output {
  elasticsearch {
    hosts => "localhost:9200"
    manage_template => false
  }
}
```

**Comment by alexharv074** [comment]
:+1:

**Comment by alexharv074** [comment]
@electrical   Any chance you could give people an update on approximately when we are likely to have this module updated properly?

**Comment by topperge** [comment]
+100

**Comment by alexharv074** [comment]
@tylerjl  Is there a new maintainer here, or is there likely to be one?  I am writing a series of blog posts on how to build a scalable logstash solution with these and other modules.  It'd be so great if I can just say "hey, the logstash module just works!"

**Comment by tylerjl** [comment]
@alexharv074 it's on our radar - it'll have a place somewhere, whether that's under some of the infrastructure I'm overhauling right now or otherwise.

**Comment by alexharv074** [comment]
@tylerjl If I send in PRs will they be merged?

**Comment by tylerjl** [comment]
@alexharv074 I'd like to get CI stable again so we can merge confidently, but once that's done, given the changes are sane, I certainly don't see why not. :+1:

**Comment by alexharv074** [comment]
@tylerjl what's the issue with the CI?  I just ran all the tests and they're fine.  There's a Travis config in place.  All looks ok?

**Comment by alexharv074** [comment]
@cdenneen Is it your understanding that the only feature that's missing for the latest Logstash is the plugin installation?

**Comment by cdenneen** [comment]
@alexharv074 yes this is one of the more important parts to get the basic functionality of 1.5+. But as other open issues have mentioned it should support templates and multi-instance support.

**Comment by tylerjl** [comment]
@alexharv074 I'm referring to the *entire* suite of tests, which include acceptance tests, which as far as I know are not running anywhere cleanly right now, including on Jenkins (where there are no executors) and Travis (where this repo is disabled and hasn't run for several couple months.)

**Comment by alexharv074** [comment]
@tylerjl  Can you guide me on what I'd need to do to get the acceptance tests working again?

**Comment by tylerjl** [comment]
@alexharv074 I'm wrapping up overhauling testing in the puppet-elasticsearch repo, which I'll then carry over into this repo and enable everyone to run the tests as long as they've got `make`, `bundler`, and `docker` available.

**Comment by alexharv074** [comment]
This sounds like a lot of work.  I doubt that many people would agree that overhauling the automated testing should take priority over basic functionality.  Test driven development is great, but right now, we don't have a working product to test, and we haven't had one since Logstash 1.5 was released about one year ago.

**Comment by alexharv074** [comment]
@tylerjl   I have written the Elasticsearch chapter of my blog post series [here](http://razorconsulting.com.au/building-a-highly-available-elk-solution-with-puppet-part-ii-elasticsearch-backend.html).  I'm going to write another article discussing the base class and the Kibana 4 node.  I need this module to work, or I'm just going to have to fork it, fix it, and tell people to use my version.

**Comment by tylerjl** [comment]
@alexharv074 totally understand the timeline you're working under. If I can't get caught up to this module in time, we can always PR your downstream changes into this module later so you aren't blocked.

**Comment by alexharv074** [comment]
Well it seems you're doggedly resisting my efforts to be the squeaky wheel!  Fair enough.  The bigger issue is I feel this makes both Puppet and Elastic.co look bad.  I can't for the life of me understand why so much effort would have gone into the Elasticsearch Puppet module apparently at the expense of this one.  Anyhow, I realise you're new to this role so I'll leave you alone now.  Thanks for all your efforts.

**Comment by lbischof** [comment]
Thanks @jarpy! I really hope this module will get it's much needed update and your test rework is one step in the right direction.

**Comment by jarpy** [comment]
The acceptance tests are now running well in Travis, and the modern (>= 1.5.0) plugin system is now supported by the module.

I'll try now to define what complete 2.0 support looks like, so we can get everyone rolling.

Specific requests are very welcome at this stage. Thanks.

**Comment by jarpy** [comment]
All _existing_ functionality is now working and tested with Logstash 2.x, including the new plugin support. I'm going to declare the 2.0 work as "minimally done", and close this issue.

I'm certainly not saying that there's nothing left to do! But if you all could help me by creating individual issues for bugs and features, I'll be able to clearly see what the hot topics are, and hopefully deliver faster for you.

Let me know what's next! :dart: 

Thanks.
