### ISSUE TITLE
Installing community-based plugins

### ISSUE THREAD

**Issue by pscadiz** [elastic/puppet-logstash#253]
Hi,

Would just like to ask if installing community-based plugins is configurable via this module. There's no mention of installing modules from other projects with puppet-logstash, only installing custom plugins specifying the path to the .rb file.

Would specifically like to use the cloudtrail codec plugin. https://github.com/logstash-plugins/logstash-codec-cloudtrail.git

Thanks and regards,
Paolo

**Comment by electrical** [comment]
Hi,

The planning is to have a large rewrite of the current module with all the new goodness i've learned when building out the ES module further.
This will also include code to install plugins including custom things.
I'm afraid I don't have an ETA yet :-(

**Comment by madAndroid** [comment]
+1 - would like to be able to install the [cloudwatch](https://github.com/EagerELK/logstash-input-cloudwatch) plugin in the suggested way

**Comment by jarpy** [comment]
Support for installing Gems from RubyGems.org, local files, and the Puppet file server has now been merged into master.

Hopefully this meets your requirements. Thanks!
