### ISSUE TITLE
Patterns fail due to permissions if logstash_user and logstash_group are not specified

### ISSUE THREAD

**Issue by gingerwizard** [elastic/puppet-logstash#255]
The patterns directory is created with root permissions.  If the logstash_user and logstash_group are not set this directory ownership is never changed.  However, the service starts with the default user of logstash.  The patterns directory can therefore not be accessed by Logstash resulting in a failure.

Propose either the default value of the logstash_user being 'logstash' OR the service starting under root by default.

**Comment by jarpy** [comment]
The patterns directory is now owned by `$logstash_user`, so this should be fixed.
