### ISSUE TITLE
Service not correctly enabled on CentOS when serviceprovider == 'init'

### ISSUE THREAD

**Issue by madAndroid** [elastic/puppet-logstash#256]
We've noticed this happening on CentOS7 nodes which have had logstash intentionally disabled in order to have it managed (re-enabled) by puppet during their initial provisioning.

It turns out that when `provider   => 'init'`, the service is not enabled correctly .. but it does get enabled correctly when the default provider is used.

**Comment by madAndroid** [comment]
Confirmation using `puppet resource`:
```
[root@test-host ~]# puppet resource service logstash enable=false
Notice: /Service[logstash]/enable: enable changed 'true' to 'false'
service { 'logstash':
  ensure => 'running',
  enable => 'false',
}
[root@test-host ~]# chkconfig | grep logstash

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

logstash        0:off   1:off   2:off   3:off   4:off   5:off   6:off
[root@test-host ~]# puppet resource service logstash enable=true provider=init
service { 'logstash':
  ensure => 'running',
}
[root@test-host ~]# chkconfig | grep logstash

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

logstash        0:off   1:off   2:off   3:off   4:off   5:off   6:off
```

**Comment by alexharv074** [comment]
This is due to the following Puppet bug, which Puppet Labs are promising to have resolved in their next iteration.  https://tickets.puppetlabs.com/browse/PUP-5296

**Comment by cdenneen** [comment]
I don't have this issue on CentOS 7 with LS versions 1.5-2.2. 
Logstash always enabled and run. 
Instead of reviewing chkconfig can you review systemctl status logstash?

**Comment by alexharv074** [comment]
What version of Puppet are you using @cdenneen ?  The bug only affects recent releases of Puppet 4.

**Comment by madAndroid** [comment]
I've been seeing this issue on puppet 3.7.5, on CentOS 7

**Comment by cdenneen** [comment]
Pretty sure I've tested on 3.8 and 4.2 but will double check this week.

**Comment by alexharv074** [comment]
The bug PUP-5296 was apparently introduced in Puppet 4.2.1 so I'd say that I was wrong, and we're looking at a different bug.

**Comment by jarpy** [comment]
This is (hopefully) fixed by [this change](https://github.com/elastic/puppet-logstash/commit/c5fe7ec406569d3076d8f26e73be69bcad7f2643#diff-e629c52d01db81f4efd0e6c9c31335e7R127).

**Comment by madAndroid** [comment]
@jarpy - thanks for sorting this out :) Any chance you could release a new version on the forge / and or a tag here in Github? The last tag/release is 15/04/2014, and we try and avoid installing directly from master wherever possible.

**Comment by jarpy** [comment]
Absolutely. Good calls all 'round, @madAndroid.

I just published the current code to the Forge as version `0.6.0` and pushed a matching tag here.

**Comment by madAndroid** [comment]
That's awesome, thanks very much @jarpy :)

**Comment by jarpy** [comment]
:beers:
