### ISSUE TITLE
File_concat unresolvable

### ISSUE THREAD

**Issue by frankvolkel** [elastic/puppet-logstash#261]
I'm getting the following error on puppet-logstash when using logstash::configfile: 

```Error: Failed to apply catalog: Could not find dependent File_concat[ls-config] for File_fragment[configname] at /etc/puppet/modules/logstash/manifests/configfile.pp:63```

Versions are: 

```/etc/puppet/modules
└─┬ elasticsearch-logstash (v0.5.1)
  ├── ispavailability-file_concat (v0.3.0)
  └── puppetlabs-stdlib (v4.9.0)
```

puppet (v3.8.3)

manifest: 
```logstash::configfile { 'configname':
    source => 'puppet:///modules/logstash/logstash-nginx.conf'
}```

I've already tried a tar.gz install of the module instead of using puppetforge.

**Comment by electrical** [comment]
Hi,

That's weird.
Could you remove the ispavailability one and use electrical-file_concat ?
I still need to update the LS module to use the new name space, sorry for that :-(

**Comment by frankvolkel** [comment]
I'm still getting the same error despite forcing removal of ispavailability-file_concat and replacing it with electrical-file_concat

**Comment by electrical** [comment]
did you restart the puppet server? Since its a native type it might not be loaded correctly.

**Comment by frankvolkel** [comment]
Yes, killed the previous puppet master process and relaunched a new daemonized puppet process; same result :(

**Comment by electrical** [comment]
That's very weird.
Can you gist the whole puppet part you use?

**Comment by frankvolkel** [comment]
My puppet-logstash config is already as simple as it can get: 

https://gist.github.com/frankvolkel/aced01ab0d4c0db2e1ab

My installed puppet modules now (after swapping out ispavailability-file_concat for electrical-file_concat): 

````
├─┬ puppetlabs-apache (v1.7.0)
│ ├── puppetlabs-stdlib (v4.9.0)
│ └── puppetlabs-concat (v1.2.4)
├─┬ razorsedge-vmwaretools (v4.8.1)
│ └── wolfspyre-vmware_puppetfact (v0.2.2)
├── yguenane-authconfig (v0.6.0)
├── saz-timezone (v3.3.0)
├── jbussdieker-daemontools (v0.0.3)
├── walkamongus-sssd (v1.2.0)
├── sslkey (???)
├── spiette-selinux (v0.5.4)
├── electrical-file_concat (v1.0.1)
├── puppetlabs-firewall (v1.7.1)
├── saz-resolv_conf (v3.0.5)
├── thias-glusterfs (v0.0.3)
├─┬ m0byd1ck-remi (v1.0.3)
│ └── stahnma-epel (v1.2.0)
├── erwbgy-limits (v0.3.1)
├── rodjek-logrotate (v1.1.1)
├─┬ elasticsearch-logstash (v0.5.1)
│ └── UNMET DEPENDENCY ispavailability-file_concat (>= 0.1.0)
├─┬ AlexCline-mounts (v0.3.1)
│ ├── AlexCline-fstab (v0.5.4)
│ └── AlexCline-dirtree (v0.2.1)
├─┬ mayflower-php (v3.4.2)
│ ├── puppetlabs-apt (v2.2.0)
│ ├── puppetlabs-inifile (v1.4.2)
│ ├── darin-zypprepo (v1.0.2)
│ └─┬ example42-yum (v2.1.25)
│   └── example42-puppi (v2.1.12)
├─┬ fsalum-newrelic (v4.1.1)
│ └─┬ puppet-download_file (v1.2.1)
│   └── puppetlabs-powershell (v1.0.5)
├── jfryman-nginx (v0.2.7)
├── puppetlabs-ntp (v4.1.0)
└── razorsedge-network (v3.6.0)
````

**Comment by electrical** [comment]
Ahhh okay. You are missing a call to the main logstash class which sets up a lot of other stuff as well.
for example:
```
class { 'logstash': 
  manage_repo => true,
  repo_version => '2.1',
  java_install => true,
}
```

**Comment by frankvolkel** [comment]
How could I have missed that out! It works now :)

**Comment by electrical** [comment]
No worries :-) glad its solved. You can close the issue if you have no further questions.
