### ISSUE TITLE
why software_provider "custom" is missing

### ISSUE THREAD

**Issue by mizeng** [elastic/puppet-logstash#273]
as in title, "custom" provider exists in early version of puppet-logstash, but missing in current version. Can someone help to let me know why?

**Comment by jarpy** [comment]
Hi. What did the `custom` provider do? Did it attempt to install from a `.tar.gz` file?

**Comment by mizeng** [comment]
Yes. As in early version, I can specify to install logstash from a private url. https://github.com/elastic/puppet-logstash/blob/0.3.4/manifests/service.pp#L103

**Comment by jarpy** [comment]
Ah OK. It's possible to [install a packaged version from an explicit URL](https://github.com/elastic/puppet-logstash#using-an-explicit-package-source), but `.tar` and `.jar` files are not supported.

Is a packaged version OK? Logstash provides packages for most supported platforms.

https://www.elastic.co/support/matrix

**Comment by mizeng** [comment]
Thanks a lot. But tar.gz is not supported? Could not retrieve catalog from remote server: Error 400 on SERVER: Unknown file extention "gz".

**Comment by jarpy** [comment]
Very welcome!

Good luck, and Happy Logstashing.
