### ISSUE TITLE
does it support multiple config files in /etc/logstash/conf.d

### ISSUE THREAD

**Issue by mizeng** [elastic/puppet-logstash#279]
I've wrote puppet code as below:
```
 logstash060::configfile { 'basic_config':
    content => 'input { tcp { port => 2000 } } output { null {} }'
  }

logstash060::configfile { 'date_timestamp':
    content => 'filter { date { match => [\'yyyy-MM-dd HH:mm:ss.SSSZ\', \'dd-MMM-YYYY::HH:mm:ss\', \'yyyy-MM-dd HH:mm:ss,SSS\', \'yyyy-MM-dd HH:mm:ss\', \'EEE MMM DD HH:mm:ss YYYY\', \'dd/MMM/yyyy:HH:mm:ss Z\'] } }'
  }

```

And only see one file `logstash.conf` under `/etc/logstash/conf.d`. Can I have multiple config files with customized file name in this config folder?

**Comment by jarpy** [comment]
The current version [accepts multiple config fragments](https://forge.puppet.com/elasticsearch/logstash#logstash-config-files), then combines them into a single large file.

A future version will simply create multiple files, because Logstash now supports that.

**Comment by mizeng** [comment]
Thanks and look forward to that since below code(exist in different puppet class) to add multiple filters isn't work now:
```
logstash::configfile { 'date_timestamp':
    content => 'filter { date { match => [\'yyyy-MM-dd HH:mm:ss.SSSZ\', \'dd-MMM-YYYY::HH:mm:ss\', \'yyyy-MM-dd HH:mm:ss,SSS\', \'yyyy-MM-dd HH:mm:ss\', \'EEE MMM DD HH:mm:ss YYYY\', \'dd/MMM/yyyy:HH:mm:ss Z\'] } }'
  }

  logstash::configfile { 'mutate_pki_token':
    content => 'filter { mutate { gsub => [\'@message\', \'MII[^\'|"]*\', \'*****\'] } }'
  }
```

**Comment by jarpy** [comment]
Cool. To avoid all those escaped qoutes, you can put your Logstash config in files and templates. Like:

``` puppet
logstash::configfile { 'configname':
  content => template('puppet:///modules/my_ls_configs/date.erb'),
}

logstash::configfile { 'configname':
  content => template('puppet:///modules/my_ls_configs/mutate.erb'),
}
```

**Comment by jarpy** [comment]
Or you could use mixed qouting, like:

```
logstash::configfile { 'date_timestamp':
    content => "filter { date { match => ['yyyy-MM-dd HH:mm:ss.SSSZ', 'dd-MMM-YYYY::HH:mm:ss', 'yyyy-MM-dd HH:mm:ss,SSS', 'yyyy-MM-dd HH:mm:ss', 'EEE MMM DD HH:mm:ss YYYY', 'dd/MMM/yyyy:HH:mm:ss Z'] } }"
}
```

Note the double-qoutes on the outside.

**Comment by mizeng** [comment]
I see. The 2 config file will combine to a conf like below
```
filter { date { match => ['yyyy-MM-dd HH:mm:ss.SSSZ', 'dd-MMM-YYYY::HH:mm:ss', 'yyyy-MM-dd HH:mm:ss,SSS', 'yyyy-MM-dd HH:mm:ss', 'EEE MMM DD HH:mm:ss YYYY', 'dd/MMM/yyyy:HH:mm:ss Z'] } } filter { mutate { gsub => ['@message', 'MII[^'|"]*', '*****'] } }
```

You can see there's 2 "filter" keywords in the conf file which is obviously wrong. So how can I separate multiple filter fragments in multiple logstash::configfile resource?


BTW, may I ask why something like https://github.com/elastic/puppet-logstash/blob/0.3.1/manifests/filter/grok.pp is not available now? It is very convenient for this use case. 
I can just write as below with **date** and **mutate** resource:
```
logstash::filter::date {'timestamp':
        match => ['yyyy-MM-dd HH:mm:ss.SSSZ',
                'dd-MMM-YYYY::HH:mm:ss',
                'yyyy-MM-dd HH:mm:ss,SSS',
                'yyyy-MM-dd HH:mm:ss',
                'EEE MMM DD HH:mm:ss YYYY',
                'dd/MMM/yyyy:HH:mm:ss Z'],
    }

logstash::filter::mutate {'pki-token-filter':
      gsub => ["@message", "MII[^\\\'|\"]*", "*****"]
    }
```

**Comment by jarpy** [comment]
Multiple filter blocks is fine, Logstash doesn't mind.

I'm not sure why the code you mention was removed, but I know it's a big topic.

Personally, I don't see a lot of value in creating a one-to-one abstraction over Logstash configuration syntax.

I really do encourage you to write your filters as files or templates, rather than inline strings.

As a file, your date filter is just:
```
filter {
  date {
    match => [
      'yyyy-MM-dd HH:mm:ss.SSSZ',
      'dd-MMM-YYYY::HH:mm:ss',
      'yyyy-MM-dd HH:mm:ss,SSS',
      'yyyy-MM-dd HH:mm:ss',
      'EEE MMM DD HH:mm:ss YYYY',
      'dd/MMM/yyyy:HH:mm:ss Z'
    ]
  }
}
```

I don't think that's any less complex than:
```
logstash::filter::date {'timestamp':
        match => ['yyyy-MM-dd HH:mm:ss.SSSZ',
                'dd-MMM-YYYY::HH:mm:ss',
                'yyyy-MM-dd HH:mm:ss,SSS',
                'yyyy-MM-dd HH:mm:ss',
                'EEE MMM DD HH:mm:ss YYYY',
                'dd/MMM/yyyy:HH:mm:ss Z'],
    }
```

And it is certainly a lot nicer than:
```
logstash::configfile { 'date_timestamp':
    content => 'filter { date { match => [\'yyyy-MM-dd HH:mm:ss.SSSZ\', \'dd-MMM-YYYY::HH:mm:ss\', \'yyyy-MM-dd HH:mm:ss,SSS\', \'yyyy-MM-dd HH:mm:ss\', \'EEE MMM DD HH:mm:ss YYYY\', \'dd/MMM/yyyy:HH:mm:ss Z\'] } }'
  }
```

I would only use inline string configuration in very, very simple cases.

**Comment by mizeng** [comment]
you're right. I may just don't like to maintain lots of files for filters, but like to have them in one puppet class.

**Comment by mizeng** [comment]
And I also don't like only one single large conf file rather than several small conf files(each for different functions).
