### ISSUE TITLE
How to use in a server which has default jdk version 1.6

### ISSUE THREAD

**Issue by mizeng** [elastic/puppet-logstash#285]
I'm upgrading logstash from 1.1.x to 2.3.2 using puppet-logstash. But met problems:

Although puppet code installed JDK 1.7 but the default JDK in the system is still JDK 1.6. So new logstash agent will get failed due to wrong default JDK version. 
So I have to manually run command `update-alternatives --config java` to change default JDK.

Can we add puppet code to do it automatically? Or can we not using `/usr/bin/java` to start logstash but using the exact JDK 1.7 path like `/usr/lib/jvm/java-7-openjdk-amd64//bin/java` in puppet code?

**Comment by jarpy** [comment]
The support for installing Java in this module is pretty basic, and I personally think it should be removed. It really breaks one the core rules of good Puppet coding to have a module called "logstash" installing Java.

I'd suggest trying the [official Java module](https://forge.puppet.com/puppetlabs/java), and asking puppet-logstash to stop messing with Java altogether. I intend to remove all Java support from the module in the future, and have it depend on puppetlabs-java instead.
