### ISSUE TITLE
The logstash::logstash_user and logstash::logstash_group parameters should be set to 'logstash' when installing from packages

### ISSUE THREAD

**Issue by trevor-vaughan** [elastic/puppet-logstash#289]
Presently, these are hard-coded as 'root' in logstash::params. However, this causes a failure to start if you've created your configuration items with a least privilege restriction of 0640 for file modes.

**Comment by elconas** [comment]
+1

**Comment by jarpy** [comment]
This bug is resolved in the latest version. User and group now default to `logstash`.
