### ISSUE TITLE
Use supported Java module

### ISSUE THREAD

**Issue by edestecd** [elastic/puppet-logstash#293]
Stop reinventing the wheel and replace

``` puppet
class logstash::java
```

with https://forge.puppet.com/puppetlabs/java

**Comment by jarpy** [comment]
I think we should do a major version for the release of Logstash 5.0 that includes this change too.

**Comment by jarpy** [comment]
The latest version of the module eschews managing Java completely, in alignment with the "roles and profiles" pattern. No more crufty Java installation code in the module! :)
