### ISSUE TITLE
Logstash 1.3.3 and 2.3.4 from same puppet master

### ISSUE THREAD

**Issue by fribergr** [elastic/puppet-logstash#297]
Hi,

We currently have Logstash 1.3.3 deployed to our environments, and we've begun replacing it with Logstash 2.3.4.
The first though was to do this in our testing-environment first, with this puppet module (as we already use it for 1.3.3).

However, due to the fact that the new version of this module does not support the old version of logstash, I'll have to run two different versions of them at the same time. Is this possible?
Or do I need to rename one of the module versions to something else? If so, any pointers on what I need to be aware of when doing this?

Best regards,
Robin

**Comment by cdenneen** [comment]
You'd create 2 different Puppet environments.
In one you can run older version of the logstash module and in new you
could run the new one.
Once you have migrated to newer version of logstash you could do away with
the separate environment in puppet.

**Comment by jarpy** [comment]
Absolutely. Environments are a common way to achieve this. A Puppet environment is a separate copy of your all your configuration and code that is applied to only those hosts configured to be in that environment.

https://docs.puppet.com/puppet/latest/reference/environments.html

It's very common to have each environment check out a different branch of your Puppet code from version control. This one of the (many) great reasons to version control your Puppet.

**Comment by fribergr** [comment]
Sorry for slow response.
I'm just wondering if I will not encounter bug [PUP-731](https://tickets.puppetlabs.com/browse/PUP-731) if I run with multiple environments for this?
We are currently running Puppet Enterprise 3.3 I believe.

**Comment by jarpy** [comment]
I think you'll be fine. The module is implemented in pure Puppet, so there are no native (ruby) types in there.

Good luck with your multi-environment future! :beers:
