### ISSUE TITLE
Logstash enable changed 'false' to 'true'

### ISSUE THREAD

**Issue by pietervogelaar** [elastic/puppet-logstash#300]
Ik keep getting this notice (which causes the server to get the status "changed" in the Puppet Enterprise dashboard):

```
Notice: /Stage[main]/Logstash::Service/Logstash::Service::Init[logstash]/Service[logstash]/enable: enable changed 'false' to 'true'
```

OS: RHEL 7.2 (with SELinux)

**Comment by eLvErDe** [comment]
Hello,

I can confirm this broken behavior on all my Debian Jessie machines as well !

Regards, Adam.

**Comment by bazzie** [comment]
Same behavior on CentOS 7

**Comment by jarpy** [comment]
With the completion of work in #312, this issue should be resolved for current Logstash versions.
