### ISSUE TITLE
Mismatch between Modulefile and metadata.json

### ISSUE THREAD

**Issue by lhirdman** [elastic/puppet-logstash#301]
I am trying to create a git based repo for my Katello installation but this fails when running "puppet module build" with the following error:
> Warning: Modulefile is deprecated. Merging your Modulefile and metadata.json.
> Error: Dependency conflict for elasticsearch-logstash: Dependency puppetlabs/stdlib was given conflicting version requirements >= 3.2.0 and >= 3.2.0 <5.0.0. Verify that there are no duplicates in the metadata.json or the Modulefile.
> Error: Try 'puppet help module build' for usage

Not a big issue as I can just add the package manually to the repo in Katello but it seems to be an easy fix to just update the _Modulefile_ file to match _metadata.json_ .

**Comment by jarpy** [comment]
I just deleted the Modulefile. Hopefully that does the trick!
