### ISSUE TITLE
Add ability to override restart command

### ISSUE THREAD

**Issue by pysysops** [elastic/puppet-logstash#315]
Hi, 

Currently the service restart command is whatever the detected service managers command is, usually along the lines of: `service logstash restart`

This is great until someone pushes up a broken config and logstash fails to start. 

By passing a restart parameter to the service resource it would allow users to set there own restart command to something like: `service logstash configtest && service logstash restart`

We could go further than this and pass in a validate_cmd to file_fragment(s) which would run a command to validate the temporary file before replacing the configuration and restarting the logstash service? 

I'll create a PR for the first issue (service restart override) with tests, docs etc... 

Thanks, 

Tim Birkett.

**Comment by jarpy** [comment]
Thanks Tim,

If you're planning to hack on this module, please note that development effort has switched to the `5.x` branch for the time being. The current `master` supports Logstash 2, where the init system is kind of a mess. Logstash 5 (and thus the `5.x` branch of this module) has much better init handling with, notably, proper support for systemd.
