### ISSUE TITLE
Plugins installation fails as logstash user

### ISSUE THREAD

**Issue by jarro2783** [elastic/puppet-logstash#320]
Plugins are installed by this module as the logstash user, which doesn't appear to work:

```
  Exec {
    path    => '/bin:/usr/bin',
    user    => $logstash::logstash_user,
    timeout => 1800,
  }
```

The failure looks like:
```
Notice: /Stage[main]/Logstash_indexer/Logstash::Plugin[logstash-filter-anonymize]/Exec[install-logstash-filter-anonymize]/returns: Make sure that `gem install arr-pm -v '0.0.10'` succeeds before bundling.
```

A look inside the gems directory in the logstash installation shows the gem directories owned by a mix of `root` and `logstash`. The `arr-pm` gem in particular is owned by root, which I think causes the gem installation to fail.

If I run `sudo /usr/share/logstash/bin/logstash-plugin install plugin-name` manually then the affected plugin installs without error.

**Comment by jarpy** [comment]
Thanks, I'll investigate.

It could get interesting, however, because it's not so long ago that the [exact opposite behaviour was reported as bug](https://github.com/elastic/puppet-logstash/issues/307)! 😃

**Comment by jarpy** [comment]
I can't replicate the problem with this manifest:

``` puppet
class { 'logstash': }
logstash::plugin { 'logstash-filter-anonymize': }
```

After applying it, no Logstash files are owned by anybody but the `logstash` user:

```bash
root@localhost:~# find /usr/share/logstash/ ! -user logstash
root@localhost:~# 
```
Has your target system been around for a while? Is the root ownership maybe some leftover state?

Perhaps you can resolve everything with as little as `chown -R logstash /usr/share/logstash`.

**Comment by jarro2783** [comment]
Well that's interesting. These are fresh hosts, so that's not the problem.

It might be something that Ubuntu does. I will look into it more next year once I am back from holidays.

**Comment by jarro2783** [comment]
I found the problem. We were running `logstash-plugin install --development` as root in our puppet code. This was changing the ownership of some of the installed gems. The current solution appears to be the right one.

**Comment by jarpy** [comment]
Thanks for closing the loop @jarro2783. 👍
