### ISSUE TITLE
Changing log.level and path.logs 

### ISSUE THREAD

**Issue by smitjainsj** [elastic/puppet-logstash#322]
_**Team,**_

How can I change the "log.level" and "path.logs" in logstash, I know one way to make change in  module itself. But I am using hiera for  installation purpose, it would be grateful if you can guide me.

Module Version : 5.0.3
Ubuntu: 14.04

**Comment by jarpy** [comment]
Hi @smitjainsj,

Both `log.level` and `path.logs` are specified in the `settings` parameter. It expects a hash of key/values, so if you want to set them with Hiera (and assuming you are using the YAML backend for Hiera, you can set:

``` yaml
logstash::settings:
  log.level: debug
  path.logs: /tmp
```

**Comment by jarpy** [comment]
Hopefully this worked for you, @smitjainsj.
