### ISSUE TITLE
Inconsistent sort order of hashes in jvm.options.erb and logstash.yml.erb

### ISSUE THREAD

**Issue by tkuther** [elastic/puppet-logstash#332]
I'm having an issue on our production servers with the order of options in
template/jvm.options.erb and template/logstash.yml.erb

The servers run CentOS 6 with Ruby 1.8 and Puppet 3.8.7. Upgrading to Puppet 4 is no option (yet).

The order changes on every puppet run, causing a refresh of the logstash process.
Diff for last run:
```
--- /etc/logstash/logstash.yml	2017-03-20 12:13:46.528985209 +0100
+++ /tmp/puppet-file20170320-56750-odzb3q-0	2017-03-20 12:43:45.354662699 +0100
@@ -1,4 +1,4 @@
 --- 
-  path.config: /etc/logstash/conf.d
   path.data: /var/lib/logstash
+  path.config: /etc/logstash/conf.d
   path.logs: /var/log/logstash
```
The previous run:
```
-  path.logs: /var/log/logstash
-  path.data: /var/lib/logstash
   path.config: /etc/logstash/conf.d
+  path.data: /var/lib/logstash
+  path.logs: /var/log/logstash
```
..and so on and on and on and on.

The hash should be sorted, like `<% @jvm_options.sort.each do |line| -%>`.
This is already done in template/startup.options.erb, works fine there.

**Comment by jarpy** [comment]
The `jvm.options` is now sorted. fb110915945f4e97a6dde093d94d869e96252866

Getting `logstash.yml` to be deterministic is non-trivial under Ruby 1.8. We could consider implementing a recursive deep sort of the hash, but it sounds like a high-complexity, high-risk solution.
