### ISSUE TITLE
Jenkins build fail

### ISSUE THREAD

**Issue by storm49152** [elastic/puppet-logstash#336]
Hi,

We're using Puppet 4.9.4 (PC1) and the logstash-5.0.4 module.

We're periodically running our code through Jenkins and a build stops when validating logstash:

+ /opt/puppetlabs/bin/puppet parser validate --render-as s --modulepath=modules ./modules/logstash/manifests/service.pp

Error: Could not parse for environment production: This Name has no effect. A value was produced and then forgotten (one or more preceding expressions may have the wrong form) at /var/lib/jenkins/workspace/puppet4/modules/logstash/manifests/service.pp:143:5
+ exit 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE

This is about:
```
  if $::logstash::restart_on_change {
    File<| tag == 'logstash_config' |> ~> Service['logstash']
    logstash::Plugin<| |> ~> Service['logstash']
  }
```
Specifically this line: logstash::Plugin<| |> ~> Service['logstash']

I don't know if this is a real issue: a normal puppet agent run works fine, but Jenkins stops the build because of puppet parser saying something's wrong. Please advise.

Thanks.

**Comment by jarpy** [comment]
Hi,

Sorry. I'm really not sure what's going on there. We run `puppet parser validate` with every commit, as part of the continuous integration tests, and I can't get it to fail locally:

```
$ bundle exec puppet --version
4.9.4
$ bundle exec puppet parser validate manifests
$ 
```

Having said that, [`service.pp:143`](https://github.com/elastic/puppet-logstash/blob/937a27cd45b9f703a975a5c5135dde2525115c6b/manifests/service.pp#L143) is using the [spaceship operator](https://docs.puppet.com/puppet/4.9/lang_collectors.html), so it's a little magical. Strange things can, and do happen with things like that.

**Comment by storm49152** [comment]
I just re-downloaded the module from GitHub and executed "puppet parser validate" on the code, which works without issues. Don't know what was wrong with it. (Should have done this before asking, but thanks for confirming anyway.)

**Comment by jarpy** [comment]
No problem. Thanks for reporting back.
