### ISSUE TITLE
Make this module friendly to users who store their logstash config in a separate git (or other) repo

### ISSUE THREAD

**Issue by nick-george** [elastic/puppet-logstash#338]
As it stands, this module doesn't support users who store their logstash configs in a repository separately to their puppet config. I suspect most users who have non-trivial logstash configs would rather store their configs outside of Puppet. 

Here are a couple of the issues that prevent the use of a git repo: 
- Ownership of the files under /etc/logstash (they are all forced to be root only, something that was previously configurable)
- The /etc/logstash/conf.d (and /etc/logstash) are created using puppet, meaning that any vcsrepo resource cannot be created there - they have to be placed somewhere else, or underneath those dirs. 
- No direct support for the vcsrepo resource anywhere in the code

Ideally, the module would either allow the user to store their entire /etc/logstash dir in git, or even just particular subdirs, such as /etc/logstash/conf.d. 

Thanks,
Nick

**Comment by jarpy** [comment]
Sorry for the slow reply.

I see the primary use of this module as allowing people to programatically generate pipeline configuration with Puppet and ERB. Apart from that, the module doesn't really do very much except install the package and start the service.

Having said that, it's easy to manage your pipeline config another way and still use the module. Just put the config outside the location that the module is trying to manage and let Logstash know:

```puppet
$pipeline = '/usr/local/etc/logstash/config/'

class { 'logstash':
  manage_repo  => true,
  repo_version => '5.x',
  settings => {
    'path.config' => $pipeline,
  }
}

vcsrepo { $pipeline:
  ensure   => latest,
  provider => git,
  source   => 'https://github.com/jarpy/logstash-config.git',
  notify   => Service['logstash'],
}
```
Is something like that appropriate for your site?

Cheers,
Toby.
