### ISSUE TITLE
Support for offline plugin packs served via puppet

### ISSUE THREAD

**Issue by Ymbirtt** [elastic/puppet-logstash#347]
The `logstash-plugin` subcommand allows plugins to be packed into[ offline-installable packages](https://www.elastic.co/guide/en/logstash/current/offline-plugins.html). Currently, this puppet module allows individual gems to be installed from a `puppet:///` url, but doing this still contacts https://rubygems.org to download dependencies, which isn't very useful for an offline deployment.

**Comment by jarpy** [comment]
Fixed in #348
