### ISSUE TITLE
Logstash getting installed in /opt

### ISSUE THREAD

**Issue by JetFault** [elastic/puppet-logstash#351]
Whenever I try to use this to install logstash version 5.1.1, it installs it into `/opt/logstash` and because of this fails on plugin installation because of the lookup to hardcoded `/usr/share/logstash` as the `$home_dir`.

Doing this on `CentOS 7.3.1611` with Puppet Version `4.9.4`.

Here is my manifest:
```
  class { 'logstash':
    version => '5.1.1'
  }

  logstash::plugin { 'logstash-output-amazon_es': }

  logstash::configfile { 'basic_config':
    content => 'input { tcp { port => 2000 } } output { null {} }'
  }
```

Any hints?

**Comment by jarpy** [comment]
That's very strange.

Thanks for providing a manifest for reproduction.  Sadly, when I run that manifest in the [Centos 7.3 Vagrant box](https://github.com/elastic/puppet-logstash/blob/master/Vagrantfile) that I use for exploratory testing, I don't see the behaviour that you do.

Is it possible that you're getting the wrong (or multiple) versions of Logstash installed? Prior to the 5.0 release, Logstash packages _did_ install to `/opt/logstash`. 

What do you get as the output of `/opt/logstash/bin/logstash --version`?
How about `rpm -qa | grep logstash`?

You might also want to check your YUM repository definitions to make sure you only have references to the 5.x repository.

**Comment by JetFault** [comment]
I actually do have multiple versions of logstash. This is why it sometimes fails the installation saying version 2.X is installed. This is a brand new box I make through CloudFormation, so I was wondering where this old version was being installed from.

**Comment by JetFault** [comment]
On first puppet run this shows up: 
```
Error: Could not update: Execution of '/bin/rpm -U --oldpackage /tmp/logstash-2.3.3-1.noarch.rpm' returned 1: package logstash-1:2.3.3-1.noarch is already installed
Error: /Stage[main]/Logstash::Package/Package[logstash]/ensure: change from 1:2.3.3-1 to 5.1.1 failed: Could not update: Execution of '/bin/rpm -U --oldpackage /tmp/logstash-2.3.3-1.noarch.rpm' returned 1: package logstash-1:2.3.3-1.noarch is already installed
```

So somehow logstash 2.3.3 is installed on this box. Gonna do more digging if it is installed pre puppet run.

**Comment by JetFault** [comment]
Sorry, figured it out. We were using an old version of puppet-logstash. We had it set as the correct version in Puppetfile but our r10k run wasn't installing the correct version.
