### ISSUE TITLE
CentOS7 and puppet 5 service start issue

### ISSUE THREAD

**Issue by yupvr** [elastic/puppet-logstash#352]
Hi!
puppet agent does not create service unit.
```
CentOS Linux release 7.4.1708 (Core)
puppet --version 5.3.2
elastic-logstash (v5.3.0)

```
Manifest:
```
  include logstash
  logstash::configfile { 'basic_config':
    content => 'input { tcp { port => 2000 } } output { null {} }'
  }
```
```
# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for elastic.local
Info: Applying configuration version '1507631975'
Error: Systemd start for logstash failed!
journalctl log for logstash:
-- No entries --

Error: /Stage[main]/Logstash::Service/Service[logstash]/ensure: change from 'stopped' to 'running' failed: Systemd start for logstash failed!
journalctl log for logstash:
-- No entries --
```
```
# systemctl status logstash
Unit logstash.service could not be found.
```

**Comment by jarpy** [comment]
Hi,

The system probably doesn't have Java installed. Do you get this behaviour?

```
$ /usr/share/logstash/bin/logstash --version
Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME.
```

You should arrange for Java to be installed by your site manifest. I recommend using `puppetlabs-java`, and doing something like this:

``` puppet
include java
include logstash

Package['java'] -> Package['logstash']
```

We should be more explicit about that in the documentation. Sorry, I'll make that better.

**Comment by yupvr** [comment]
Thank you.
The reason was that Java was not installed. I thought it installing automatically. Even if install Java after it would not fix the issue. Java should be installed before Logstash.
Sorry.

**Comment by jarpy** [comment]
Nothing to be sorry about! :)

I should make it more obvious that Java needs to be installed separately.

I'm glad it's working for you now.
