### ISSUE TITLE
Apt dependency when manually managing repository

### ISSUE THREAD

**Issue by StevePorter92** [elastic/puppet-logstash#359]
When manually managing the repository, there is still a hard dependency on https://forge.puppetlabs.com/puppetlabs/apt

```puppet
class { 'logstash':
  manage_repo => false,
}
```

> Error: Could not find dependency Class[Apt::Update] for Package[logstash] at .../logstash/manifests/package.pp:122

**Comment by jarpy** [comment]
Reopening until I ship a new version to Forge.
