### ISSUE TITLE
Failing to install package from package_url

### ISSUE THREAD

**Issue by mszymo** [elastic/puppet-logstash#361]
Version 5.3.0
Puppet version 3.8.5

I've been trying to run this module by downloading the deb package from my own host but I'm getting this error:

Puppet (err): Execution of '/usr/bin/dpkg --force-confold -i /tmp/logstash-5.6.8.deb' returned 1: dpkg: error processing archive /tmp/logstash-5.6.8.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 /tmp/logstash-5.6.8.deb

However the file DOES exist in /tmp after the scripts have failed (meaning that it managed to download it from the url provided). I can even run the command above and it runs fine. 

If it is run with the deb file already in /tmp then it runs fine. Im guessing that it doesnt try to download again if the correct package is already there.

My guess is that the scripts are trying to install the deb file before it has finished downloading

**Comment by jarpy** [comment]
It certainly could be an ordering bug. They were quite common in Puppet 3.

Please be aware that Puppet 3 is end-of-life and is not supported by this module. In fact, Puppet 3 was dropped by Puppet (the company) over a year ago. If this problem can be reproduced with Puppet 4 or 5, that would be pretty interesting. We do have [acceptance tests proving that install from URL works](https://github.com/elastic/puppet-logstash/blob/master/spec/acceptance/class_logstash_spec.rb#L56,L63), so I'm leaning towards this being a bug in that obsolete version of Puppet.

**Comment by mszymo** [comment]
Just revisiting to confirm that it does work with puppet 5.5.1 and it works fine, it was just an issue with puppet 3. Closing issue.

**Comment by jarpy** [comment]
Thanks for checking in. Much appreciated.
