### ISSUE TITLE
Plugin installation fails if puppet run from directory that logstash user can't read

### ISSUE THREAD

**Issue by nick-george** [elastic/puppet-logstash#363]
Logstash module version: 6.0.2
Puppet version: 4.10

If the working directory for puppet is in a location that the logstash user can't read, plugin installation fails.  

Steps to reproduce: 
 - cd into a directory that the logstash user can't see (e.g somewhere under another user's home dir)
 - run 'sudo puppet agent -t'

`[nickg@dev test-puppet]$ sudo puppet agent -t
Info: Using configured environment 'nickg_test'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for dev.box.co
Info: Applying configuration version '1522045631'
Notice: /Stage[main]/Profiles::Logstash/Profiles::Logstash::Handle_plugin[logstash-input-beats]/Logstash::Plugin[logstash-input-beats]/Exec[install-logstash-input-beats]/returns: Errno::ENOENT: No such file or directory - /home/nickg/test-puppet`

Steps to fix: 
  - Change the exec in the plugin.pp to include a 'cwd' parameter that the user can control. 

Cheers, 
Nick

**Comment by jarpy** [comment]
Would it be sufficient to just set `cwd` to `/tmp`?

**Comment by nick-george** [comment]
I suspect it would work.

**Comment by jarpy** [comment]
Cool. I'll try that now.

**Comment by jarpy** [comment]
I couldn't replicate the bug but set the `cwd` to `/tmp` anyway.

Released as version 6.1.2 on the Forge.

**Comment by nick-george** [comment]
Thanks for that Toby!
