### ISSUE TITLE
Empty manifests causes errors in Puppet6

### ISSUE THREAD

**Issue by jacobmw** [elastic/puppet-logstash#375]
https://tickets.puppetlabs.com/browse/PUP-9190

Looks like there is a manifest that is no longer being used, but has been left behind with only comments:
manifests/package/install.pp
This file should probably just be removed.

**Comment by jarpy** [comment]
Thanks. It looks like this was fixed upstream in Puppet 6.0.3, but there's absolutely no reason for us to keep junk files around.
